### ISSUE TITLE
ERR wrong number of arguments for 'hmset' command

### ISSUE THREAD

**Issue by filipecaixeta** [filipecaixeta/dontcode#8]
```
DISCONNECTING FILES LIST: []
 ERR wrong number of arguments for 'hmset' command
 (node:16) UnhandledPromiseRejectionWarning: ReplyError: ERR wrong number of arguments for 'hmset' command
     at parseError (/backend/node_modules/redis-parser/lib/parser.js:179:12)
     at parseType (/backend/node_modules/redis-parser/lib/parser.js:302:14)
 (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 335)
```

**Comment by filipecaixeta** [comment]
Added .catch() with logging.
Waiting for the error to happen so that we can solve it.

**Comment by filipecaixeta** [comment]
Fixed on https://github.com/filipecaixeta/dontcode/blob/a88755a3c55d0b7eb9353968077ed584f8c81985/backend/src/main.ts#L83
